### ISSUE TITLE
Wrong picture used for 8bit_portrait.png

### ISSUE THREAD

**Issue by jamesjeong94** [jungraejang/portfolio_website#42]
It looks like the About Me page is using the wrong asset: `8bit_portrait.png`. Please replace it with the following [png](https://photos.app.goo.gl/HvdviWfdyJ2eeZvs7)

**Comment by jamesjeong94** [comment]
Escalating this to a SEV1 incident

**Comment by jungraejang** [comment]
Closed for being SEV 5 incident
